version: '3'
services:
  web:
    build: .
    ports:
      - "4999:4999"
  redis:
    image: "redis:latest"
  datadog-agent:
    image: "datadog/agent"
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DD_API_KEY=<MY-API-KEY>
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_ENABLED=true
      - ECS_FARGATE=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_TAGS=mytagkey:mytagvalue
